### ISSUE TITLE
jQuery use

### ISSUE THREAD

**Issue by shoudaos** [drewgreenwell/electron-angular#1]
Can you please add some documentation how to add libs, for example jQuery?
Because it throws an error when trying to run electron `"jQuery is not defined"`.
But on build without electron is working well.
I import jQuery on angular-cli.json like that: 
``` 
"scripts" : [
  "node_modules/path_to_jQuery"
]
```

**Comment by drewgreenwell** [comment]
Sorry I didn't see this note. I will add something to the documentation about this. The Angular/Typescript compiler is pretty smart. You only need to run

`npm install jquery@latest`

then at the top of any of your typescript files you simply add

`import $ from 'jquery';`
